-- Create database
CREATE DATABASE clinic;

CREATE TABLE PATIENTS (
  ID INT GENERATED ALWAYS AS IDENTITY,
  NAME VARCHAR(250) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE MEDICAL_HISTORIES (
  ID INT GENERATED ALWAYS AS IDENTITY,
  ADMITTED_AT TIMESTAMP,
  PATIENT_ID INT NOT NULL,
  STATUS VARCHAR(250) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE
);

CREATE INDEX MEDICAL_HISTORIES_PATIENTS_INDEX ON MEDICAL_HISTORIES (PATIENT_ID);

CREATE TABLE TREATMENTS (
  ID INT GENERATED ALWAYS AS IDENTITY,
  TYPE VARCHAR(250) NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE INVOICES (
  ID INT GENERATED ALWAYS AS IDENTITY,
  TOTAL_AMOUNT DECIMAL NOT NULL,
  GENERATED_AT TIMESTAMP NOT NULL,
  PAYED_AT TIMESTAMP NOT NULL,
  MEDICAL_HISTORY_ID INT NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(MEDICAL_HISTORY_ID) REFERENCES MEDICAL_HISTORIES (ID) ON DELETE CASCADE
);

CREATE INDEX INVOICES_MEDICAL_HISTORIES_INDEX ON INVOICES (MEDICAL_HISTORY_ID);

CREATE TABLE INVOICE_ITEMS (
  ID INT GENERATED ALWAYS AS IDENTITY,
  UNIT_PTICE DECIMAL NOT NULL,
  QUANTITY INT NOT NULL,
  TOTAL_PRICE DECIMAL NOT NULL,
  INVOICE_ID INT NOT NULL,
  TREATMENT_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES (ID) ON DELETE CASCADE,
  FOREIGN KEY(TREATMENT_ID) REFERENCES TREATMENTS (ID) ON DELETE CASCADE
);

CREATE INDEX INVOICE_ITEMS_INVOICES_INDEX ON INVOICE_ITEMS (INVOICE_ID);

CREATE INDEX INVOICE_ITEMS_TREATMENTS_INDEX ON INVOICE_ITEMS (TREATMENT_ID);

-- Many to Many Relationship Table
CREATE TABLE MEDICAL_HISTORIES_TREATMENTS (
  ID INT GENERATED ALWAYS AS IDENTITY,
  MEDICAL_HISTORY_ID INT NOT NULL,
  TREATMENT_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (MEDICAL_HISTORY_ID) REFERENCES MEDICAL_HISTORIES (ID) ON DELETE CASCADE,
  FOREIGN KEY(TREATMENT_ID) REFERENCES TREATMENTS (ID) ON DELETE CASCADE
);

CREATE INDEX MEDICAL_HISTORIES_TREATMENTS_ID_INDEX ON MEDICAL_HISTORIES_TREATMENTS (MEDICAL_HISTORY_ID);

CREATE INDEX MEDICAL_HISTORIES_TREATMENTS_TREATMENT_INDEX ON MEDICAL_HISTORIES_TREATMENTS (TREATMENT_ID);
